version: '3'

services:

  #Apache
  angular:
    image: karthiksurabathula/httpd:school
    container_name: httpd
    volumes:
      - E:/kube/school/httpd:/usr/local/apache2/logs
    depends_on:
      - mysql
      - springboot
    ports:
      - "8080:80"
    networks:
      - spring-boot-mysql-network
  
  #Java
  springboot:
    image: karthiksurabathula/springboot:school
    container_name: spring-boot
    volumes:
      - E:/kube/school/springboot:/usr/app/logs
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password
    healthcheck:
      test: ["CMD", "curl", "springboot:8082/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - spring-boot-mysql-network
  #DB
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: schoool
    ports:
      - "8081:3306"
    volumes:
      - E:/kube/school/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=Password
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - spring-boot-mysql-network
networks:
  spring-boot-mysql-network:
    driver: bridge