apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: school
  annotations:
    haproxy.org/check: "true"
    haproxy.org/forwarded-for: "true"
    haproxy.org/load-balance: "leastconn"
spec:
  selector:
    app: springboot
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP