apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.20
        resources:
          limits:
            memory: 1Gi
            cpu: 2000m
          requests:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Password
        - name: MYSQL_DATABASE
          value: school  
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pPassword"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 12
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pPassword"]
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: http
      port: 3306
#      nodePort: 30080
#  type: NodePort
  type: ClusterIP
