#TO enable hpa metric server should be created
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: httpd-autoscaller
  namespace: school
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: httpd
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 150Mi   
      
---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-autoscaller
  namespace: school
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: springboot
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 700Mi