apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: springboot
  namespace: school
spec:
  selector:
    matchLabels:
      app: springboot
  serviceName: springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: karthiksurabathula/springboot:school
        resources:
          limits:
            memory: 1Gi
            cpu: 2000m
          requests:
            cpu: 600m
            memory: 600Mi
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/school?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Password
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: update
        #Displays sql query(off\debug) - do not change to "debug" until required
        - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
          value: "off"
        #Displays attributes used by sql query(off\trace) - do not change to "trace" until required
        - name: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL
          value: "off"
        - name: JAVA_OPTS
          value: -Xmx512m -Xms512m -XX:MaxMetaspaceSize=128m -XX:+DisableExplicitGC -server -XX:+PrintTenuringDistribution -verbose:gc -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -Xloggc:/usr/app/logs/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/app/logs
#        command: [ "java"]
#        args: ["-jar", "-D..."]
        volumeMounts:
          - name: springboot
            mountPath: /usr/app/logs
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 3
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 120
      volumes:
        - name: springboot
          persistentVolumeClaim:
            claimName: springboot-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: school
spec:
  selector:
    app: springboot
  ports:
    - name: http
      port: 8082
#      nodePort: 30081
  type: ClusterIP
#  type: NodePort